name: food
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.12.12

    - ipykernel=6.31.0
    - ipython=9.7.0

    - requests=2.32.5
    - scrapy=2.13.4
    - selenium=4.38.0

    -pandas=2.3.3